export const LP1Data = {
  diagnosis_choice_data: ["はい", "どちらでもない", "いいえ"],
  diagnosis_end_data: [
    "質問は以上です！<br/>あなた専用の転職診断書を作成しますので少々お待ちください！",
  ],
  diagnosis_greeting_data: [
    "こんにちは！キャリミミちゃんAIです！<br/>あなたの適正職業や向いている仕事のタイプを分析します✨<br/>質問の回答に応じて分析結果が変わるので慎重に選んでくださいね！",
  ],
  diagnosis_question_data: [
    {
      question:
        "何かやらなければいけないことがある時、締切のギリギリになってしまうことはありますか？",
      score_data: [
        {
          balance: 7,
          challenge: 4,
          choice: "はい",
          contribution: 3,
          freedom: 6,
          multidisciplinary: 5,
          specialist: 2,
          stability: 1,
        },
        {
          balance: 0,
          challenge: 0,
          choice: "どちらでもない",
          contribution: 0,
          freedom: 0,
          multidisciplinary: 0,
          specialist: 0,
          stability: 0,
        },
        {
          balance: 5,
          challenge: 2,
          choice: "いいえ",
          contribution: 6,
          freedom: 1,
          multidisciplinary: 3,
          specialist: 4,
          stability: 7,
        },
      ],
    },
    {
      question:
        "やりたいことが見つかった時、後回しにせずに、すぐに始めてしまうタイプですか？",
      score_data: [
        {
          balance: 2,
          challenge: 7,
          choice: "はい",
          contribution: 3,
          freedom: 6,
          multidisciplinary: 4,
          specialist: 5,
          stability: 1,
        },
        {
          balance: 0,
          challenge: 0,
          choice: "どちらでもない",
          contribution: 0,
          freedom: 0,
          multidisciplinary: 0,
          specialist: 0,
          stability: 0,
        },
        {
          balance: 5,
          challenge: 2,
          choice: "いいえ",
          contribution: 6,
          freedom: 1,
          multidisciplinary: 3,
          specialist: 4,
          stability: 7,
        },
      ],
    },
    {
      question: "急な仕事の依頼にも、予定を調整して対応することは得意ですか？",
      score_data: [
        {
          balance: 7,
          challenge: 5,
          choice: "はい",
          contribution: 6,
          freedom: 2,
          multidisciplinary: 5,
          specialist: 1,
          stability: 4,
        },
        {
          balance: 0,
          challenge: 0,
          choice: "どちらでもない",
          contribution: 0,
          freedom: 0,
          multidisciplinary: 0,
          specialist: 0,
          stability: 0,
        },
        {
          balance: 1,
          challenge: 7,
          choice: "いいえ",
          contribution: 3,
          freedom: 5,
          multidisciplinary: 4,
          specialist: 6,
          stability: 2,
        },
      ],
    },
    {
      question:
        "周りの人が困っているとき、頼まれなくても自分から手助けすることが多いですか？",
      score_data: [
        {
          balance: 5,
          challenge: 3,
          choice: "はい",
          contribution: 7,
          freedom: 2,
          multidisciplinary: 6,
          specialist: 1,
          stability: 4,
        },
        {
          balance: 0,
          challenge: 0,
          choice: "どちらでもない",
          contribution: 0,
          freedom: 0,
          multidisciplinary: 0,
          specialist: 0,
          stability: 0,
        },
        {
          balance: 2,
          challenge: 7,
          choice: "いいえ",
          contribution: 1,
          freedom: 6,
          multidisciplinary: 4,
          specialist: 5,
          stability: 3,
        },
      ],
    },
    {
      question:
        "新しい趣味や興味を持ったとき、すぐに調べたり始めたりすることが多いですか？",
      score_data: [
        {
          balance: 1,
          challenge: 6,
          choice: "はい",
          contribution: 2,
          freedom: 4,
          multidisciplinary: 3,
          specialist: 7,
          stability: 5,
        },
        {
          balance: 0,
          challenge: 0,
          choice: "どちらでもない",
          contribution: 0,
          freedom: 0,
          multidisciplinary: 0,
          specialist: 0,
          stability: 0,
        },
        {
          balance: 7,
          challenge: 2,
          choice: "いいえ",
          contribution: 6,
          freedom: 4,
          multidisciplinary: 5,
          specialist: 1,
          stability: 3,
        },
      ],
    },
    {
      question: "初対面の人と会ったとき、自分から話しかけることが得意ですか？",
      score_data: [
        {
          balance: 2,
          challenge: 6,
          choice: "はい",
          contribution: 5,
          freedom: 4,
          multidisciplinary: 7,
          specialist: 1,
          stability: 3,
        },
        {
          balance: 0,
          challenge: 0,
          choice: "どちらでもない",
          contribution: 0,
          freedom: 0,
          multidisciplinary: 0,
          specialist: 0,
          stability: 0,
        },
        {
          balance: 6,
          challenge: 2,
          choice: "いいえ",
          contribution: 3,
          freedom: 4,
          multidisciplinary: 1,
          specialist: 7,
          stability: 5,
        },
      ],
    },
  ],
};
